# Generated by Django 3.1.5 on 2021-02-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='pic',
            field=models.ImageField(blank=True, default='defoult.jpg', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='img',
            field=models.ImageField(blank=True, default='defoult.jpg', null=True, upload_to='pics'),
        ),
    ]
