# Generated by Django 3.1.5 on 2021-02-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20210202_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses_detiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('detiles', models.CharField(max_length=500, null=True)),
                ('Date', models.CharField(max_length=200, null=True)),
                ('Tutor', models.CharField(max_length=200, null=True)),
                ('Category', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='courses_detiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.courses_detiles'),
        ),
    ]
