# Generated by Django 3.1.5 on 2021-02-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20210202_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_detiles',
            name='detiles_img',
            field=models.ImageField(blank=True, default='defoult.jpg', null=True, upload_to='pics'),
        ),
    ]
