# Generated by Django 3.1.5 on 2021-02-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='twitter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
